// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SvcPayBase.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SvcPayBase.proto</summary>
public static partial class SvcPayBaseReflection {

  #region Descriptor
  /// <summary>File descriptor for SvcPayBase.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SvcPayBaseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBTdmNQYXlCYXNlLnByb3RvKvYBChFQYXltZW50UmV0dXJuQ29kZRIQCgxO",
          "T1RfRlVOQ1RJT04QABILCgdTVUNDRVNTEAESEAoMSU5TVUZGSUNJRU5UEAIS",
          "CwoHUFdEX1JFURADEhAKDENPREVfSU5WQUxJRBAEEg8KC0FDQ19JTlZBTElE",
          "EAUSDwoLUFdEX0lOVkFMSUQQBhIRCg1QQVlfRVhDRVBZSU9OEAcSEQoNUkVD",
          "X0VYQ0VQWUlPThAIEhMKD09USEVSX0VYQ0VQWUlPThAJEhMKD0VDX0xPQURf",
          "Q09OVEVOVBAKEg8KC1BBUkFNX0VSUk9SEAsSDgoKQUNDX0xPQ0tFRBAMKrkB",
          "ChZQYXltZW50Q3JlZGVudGlhbHNUeXBlEgsKB1VOS05PV04QABIPCgtDQVJE",
          "X09OTElORRABEhAKDENBUkRfT0ZGTElORRACEg0KCVFSX09OTElORRADEg4K",
          "ClFSX09GRkxJTkUQBBIOCgpCSU9fT05MSU5FEAUSDwoLQklPX09GRkxJTkUQ",
          "BhILCgdFQ19MT0FEEAcSEAoMQ0FOQ0VMX09SREVSEBASEAoMUlJUVVJOX09S",
          "REVSEBFCOAoeY29tLm5ld2NhcGVjLmh0LnByb3RvLlByb3RvU3ZjQgpTdmNQ",
          "YXlCYXNlWgouO1Byb3RvU3ZjYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PaymentReturnCode), typeof(global::PaymentCredentialsType), }, null));
  }
  #endregion

}
#region Enums
/// <summary>
///支付返回代码
/// </summary>
public enum PaymentReturnCode {
  /// <summary>
  ///无该功能
  /// </summary>
  [pbr::OriginalName("NOT_FUNCTION")] NotFunction = 0,
  /// <summary>
  ///成功。只有这一种情况说明支付在平台是成功完成的。
  /// </summary>
  [pbr::OriginalName("SUCCESS")] Success = 1,
  /// <summary>
  ///余额不足
  /// </summary>
  [pbr::OriginalName("INSUFFICIENT")] Insufficient = 2,
  /// <summary>
  ///需要密码
  /// </summary>
  [pbr::OriginalName("PWD_REQ")] PwdReq = 3,
  /// <summary>
  ///无效编码。含解密、校验失败
  /// </summary>
  [pbr::OriginalName("CODE_INVALID")] CodeInvalid = 4,
  /// <summary>
  ///无效账户
  /// </summary>
  [pbr::OriginalName("ACC_INVALID")] AccInvalid = 5,
  /// <summary>
  ///无效密码
  /// </summary>
  [pbr::OriginalName("PWD_INVALID")] PwdInvalid = 6,
  /// <summary>
  ///支付账户异常
  /// </summary>
  [pbr::OriginalName("PAY_EXCEPYION")] PayExcepyion = 7,
  /// <summary>
  ///收款账户异常
  /// </summary>
  [pbr::OriginalName("REC_EXCEPYION")] RecExcepyion = 8,
  /// <summary>
  ///其它异常
  /// </summary>
  [pbr::OriginalName("OTHER_EXCEPYION")] OtherExcepyion = 9,
  /// <summary>
  ///圈存应答
  /// </summary>
  [pbr::OriginalName("EC_LOAD_CONTENT")] EcLoadContent = 10,
  /// <summary>
  ///支付参数错误
  /// </summary>
  [pbr::OriginalName("PARAM_ERROR")] ParamError = 11,
  /// <summary>
  ///账户锁定
  /// </summary>
  [pbr::OriginalName("ACC_LOCKED")] AccLocked = 12,
}

/// <summary>
///支付请求代码，支付类型。//支付凭据类型，支付平台根绝此类型判断业务处理分支
/// </summary>
public enum PaymentCredentialsType {
  /// <summary>
  ///通用类型
  /// </summary>
  [pbr::OriginalName("UNKNOWN")] Unknown = 0,
  /// <summary>
  ///联机卡交易
  /// </summary>
  [pbr::OriginalName("CARD_ONLINE")] CardOnline = 1,
  /// <summary>
  ///脱机机卡交易
  /// </summary>
  [pbr::OriginalName("CARD_OFFLINE")] CardOffline = 2,
  /// <summary>
  ///联机码交易
  /// </summary>
  [pbr::OriginalName("QR_ONLINE")] QrOnline = 3,
  /// <summary>
  ///脱机码交易
  /// </summary>
  [pbr::OriginalName("QR_OFFLINE")] QrOffline = 4,
  /// <summary>
  ///联机生物识别交易
  /// </summary>
  [pbr::OriginalName("BIO_ONLINE")] BioOnline = 5,
  /// <summary>
  ///脱机生物识别交易
  /// </summary>
  [pbr::OriginalName("BIO_OFFLINE")] BioOffline = 6,
  /// <summary>
  ///T6特有类型
  /// </summary>
  [pbr::OriginalName("EC_LOAD")] EcLoad = 7,
  /// <summary>
  ///其它交易类型，往后续
  /// </summary>
  [pbr::OriginalName("CANCEL_ORDER")] CancelOrder = 16,
  /// <summary>
  ///订单退款交易
  /// </summary>
  [pbr::OriginalName("RRTURN_ORDER")] RrturnOrder = 17,
}

#endregion


#endregion Designer generated code
